CREATE TABLE site (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
url VARCHAR(100) NOT NULL,
cookie_confirm VARCHAR(1000),
close_page_ad VARCHAR(1000),
status INT(1) NOT NULL, 
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
max_pages INT(3) NOT NULL, 
max_depth INT(3) NOT NULL
);


CREATE TABLE site_report (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
pages_visited INT(6) NOT NULL DEFAULT 0, 
ads_no INT(6) NOT NULL  DEFAULT 0
);