kind: Deployment
apiVersion: apps/v1
metadata:
  name: control-center
  labels:
    app: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
        - name: control-center
          image: confluentinc/cp-enterprise-control-center
          env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: {{.Release.Namespace}}-kafka:9092
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: '1'
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: '1'
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: '1'
            - name: CONFLUENT_METRICS_TOPIC_REPLICATION
              value: '1'
            - name: PORT
              value: '9021'
            - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
              value: {{.Release.Namespace}}-zookeeper:2181
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: control-center
  labels:
    app: control-center
spec:
  ports:
    - name: tcp-9021-9021-k4vk2
      protocol: TCP
      port: 9021
      targetPort: 9021
      nodePort: 30493
  selector:
    app: control-center
  type: LoadBalancer

