apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper
  labels:
    app: scrapper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
      - name: scrapper
        image: localhost:32000/scrapper:latest
        env:
        - name: GRID_ADDRESS
          value: "http://192.168.69.230:4444"
        - name: DB_URL
          value: "jdbc:mysql://mysql-mariadb.mysql:3306/scrapper"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
                name: mysql-mariadb
                key: mariadb-root-password
        - name: DB_MIN_CONN
          value: "0"
        - name: DB_MAX_CONN
          value: "2"
        - name: DB_MAX_STS
          value: "10"
        ports:
          - containerPort: 9999
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: ./ads/
            name: ads-volume
      volumes:
      - name: ads-volume
        hostPath:
          path: /home/user/ads
          type: Directory       